server:
  port: 12101

spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: DEBUG

---

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /musinsa_db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: admin
    password: 1234